source 'https://github.com/CocoaPods/Specs.git'

target 'SIFontManager', :exclusive => true do
  pod "SIFontManager", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "SIFontManager", :path => "../"
end
